[2024-02-01T00:21:55.136+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_data_into_bigquery_dag.load_data_to_bq manual__2024-02-01T00:21:52.871849+00:00 [queued]>
[2024-02-01T00:21:55.140+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_data_into_bigquery_dag.load_data_to_bq manual__2024-02-01T00:21:52.871849+00:00 [queued]>
[2024-02-01T00:21:55.140+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 2
[2024-02-01T00:21:55.151+0000] {taskinstance.py:2192} INFO - Executing <Task(GCSToBigQueryOperator): load_data_to_bq> on 2024-02-01 00:21:52.871849+00:00
[2024-02-01T00:21:55.154+0000] {standard_task_runner.py:60} INFO - Started process 14368 to run task
[2024-02-01T00:21:55.156+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'load_data_into_bigquery_dag', 'load_data_to_bq', 'manual__2024-02-01T00:21:52.871849+00:00', '--job-id', '130', '--raw', '--subdir', 'DAGS_FOLDER/load_data_into_bigquery_dag.py', '--cfg-path', '/tmp/tmpaxwdi72k']
[2024-02-01T00:21:55.157+0000] {standard_task_runner.py:88} INFO - Job 130: Subtask load_data_to_bq
[2024-02-01T00:21:55.182+0000] {task_command.py:423} INFO - Running <TaskInstance: load_data_into_bigquery_dag.load_data_to_bq manual__2024-02-01T00:21:52.871849+00:00 [running]> on host de-airflow-vm-instance-1.europe-west10-a.c.dataengineeringfinal-411911.internal
[2024-02-01T00:21:55.218+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='load_data_into_bigquery_dag' AIRFLOW_CTX_TASK_ID='load_data_to_bq' AIRFLOW_CTX_EXECUTION_DATE='2024-02-01T00:21:52.871849+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-01T00:21:52.871849+00:00'
[2024-02-01T00:21:55.221+0000] {connection.py:234} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-02-01T00:21:55.221+0000] {base.py:83} INFO - Using connection ID 'google_cloud_default' for task execution.
[2024-02-01T00:21:55.222+0000] {gcs_to_bigquery.py:379} INFO - Using existing BigQuery table for storing data...
[2024-02-01T00:21:55.223+0000] {gcs_to_bigquery.py:383} INFO - Executing: {'load': {'autodetect': True, 'createDisposition': 'CREATE_IF_NEEDED', 'destinationTable': {'projectId': 'dataengineeringfinal-411911', 'datasetId': 'ibm_stock', 'tableId': 'raw_stock_data'}, 'sourceFormat': 'CSV', 'sourceUris': ['gs://de-final-bucket-1/processed_stock_data/2024-02-01.csv'], 'writeDisposition': 'WRITE_TRUNCATE', 'ignoreUnknownValues': False, 'schema': {'fields': [{'name': 'date', 'type': 'STRING', 'mode': 'NULLABLE'}, {'name': 'open', 'type': 'FLOAT', 'mode': 'NULLABLE'}, {'name': 'high', 'type': 'FLOAT', 'mode': 'NULLABLE'}, {'name': 'low', 'type': 'FLOAT', 'mode': 'NULLABLE'}, {'name': 'close', 'type': 'FLOAT', 'mode': 'NULLABLE'}, {'name': 'volume', 'type': 'INTEGER', 'mode': 'NULLABLE'}, {'name': 'moving_average', 'type': 'FLOAT', 'mode': 'NULLABLE'}, {'name': 'daily_return', 'type': 'FLOAT', 'mode': 'NULLABLE'}, {'name': 'volatility', 'type': 'FLOAT', 'mode': 'NULLABLE'}]}, 'skipLeadingRows': 1, 'fieldDelimiter': ',', 'quote': None, 'allowQuotedNewlines': False, 'encoding': 'UTF-8'}}
[2024-02-01T00:21:55.223+0000] {bigquery.py:1596} INFO - Inserting job airflow_load_data_into_bigquery_dag_load_data_to_bq_2024_02_01T00_21_52_871849_00_00_4c8be9b8e94037fe73aaf32d19788152
[2024-02-01T00:21:55.772+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/deprojectue/miniconda3/envs/airflow_demo/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/deprojectue/miniconda3/envs/airflow_demo/lib/python3.9/site-packages/airflow/providers/google/cloud/transfers/gcs_to_bigquery.py", line 442, in execute
    job.result(timeout=self.result_timeout, retry=self.result_retry)
  File "/home/deprojectue/miniconda3/envs/airflow_demo/lib/python3.9/site-packages/google/cloud/bigquery/job/base.py", line 952, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/deprojectue/miniconda3/envs/airflow_demo/lib/python3.9/site-packages/google/api_core/future/polling.py", line 261, in result
    raise self._exception
google.api_core.exceptions.NotFound: 404 Not found: URI gs://de-final-bucket-1/processed_stock_data/2024-02-01.csv
[2024-02-01T00:21:55.775+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=load_data_into_bigquery_dag, task_id=load_data_to_bq, execution_date=20240201T002152, start_date=20240201T002155, end_date=20240201T002155
[2024-02-01T00:21:55.784+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 130 for task load_data_to_bq (404 Not found: URI gs://de-final-bucket-1/processed_stock_data/2024-02-01.csv; 14368)
[2024-02-01T00:21:55.809+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-01T00:21:55.821+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
