[2024-01-31T12:37:56.550+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_analysis_dag.process_stock_data manual__2024-01-31T12:37:47.952551+00:00 [queued]>
[2024-01-31T12:37:56.554+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_analysis_dag.process_stock_data manual__2024-01-31T12:37:47.952551+00:00 [queued]>
[2024-01-31T12:37:56.555+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 3
[2024-01-31T12:37:56.564+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): process_stock_data> on 2024-01-31 12:37:47.952551+00:00
[2024-01-31T12:37:56.567+0000] {standard_task_runner.py:60} INFO - Started process 3711 to run task
[2024-01-31T12:37:56.568+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'stock_analysis_dag', 'process_stock_data', 'manual__2024-01-31T12:37:47.952551+00:00', '--job-id', '61', '--raw', '--subdir', 'DAGS_FOLDER/stock_analysis_dag.py', '--cfg-path', '/tmp/tmpxfaw1u0y']
[2024-01-31T12:37:56.569+0000] {standard_task_runner.py:88} INFO - Job 61: Subtask process_stock_data
[2024-01-31T12:37:56.589+0000] {task_command.py:423} INFO - Running <TaskInstance: stock_analysis_dag.process_stock_data manual__2024-01-31T12:37:47.952551+00:00 [running]> on host de-airflow-vm-instance-1.europe-west10-a.c.dataengineeringfinal-411911.internal
[2024-01-31T12:37:56.629+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='onatpostac@gmail.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='stock_analysis_dag' AIRFLOW_CTX_TASK_ID='process_stock_data' AIRFLOW_CTX_EXECUTION_DATE='2024-01-31T12:37:47.952551+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-01-31T12:37:47.952551+00:00'
[2024-01-31T12:37:56.633+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/deprojectue/miniconda3/envs/airflow_demo/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/deprojectue/miniconda3/envs/airflow_demo/lib/python3.9/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/deprojectue/miniconda3/envs/airflow_demo/lib/python3.9/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/deprojectue/airflow_demo/dags/stock_analysis_dag.py", line 97, in process_stock_data
    df = pd.DataFrame.from_dict(stock_data["Time Series (Daily)"], orient='index')
KeyError: 'Time Series (Daily)'
[2024-01-31T12:37:56.635+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=stock_analysis_dag, task_id=process_stock_data, execution_date=20240131T123747, start_date=20240131T123756, end_date=20240131T123756
[2024-01-31T12:37:56.642+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 61 for task process_stock_data ('Time Series (Daily)'; 3711)
[2024-01-31T12:37:56.660+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-01-31T12:37:56.671+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
