[2024-01-31T12:27:01.573+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_analysis_dag.get_and_store_gpt_advice manual__2024-01-31T12:26:47.777766+00:00 [queued]>
[2024-01-31T12:27:01.578+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_analysis_dag.get_and_store_gpt_advice manual__2024-01-31T12:26:47.777766+00:00 [queued]>
[2024-01-31T12:27:01.578+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 3
[2024-01-31T12:27:01.588+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): get_and_store_gpt_advice> on 2024-01-31 12:26:47.777766+00:00
[2024-01-31T12:27:01.591+0000] {standard_task_runner.py:60} INFO - Started process 3470 to run task
[2024-01-31T12:27:01.594+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'stock_analysis_dag', 'get_and_store_gpt_advice', 'manual__2024-01-31T12:26:47.777766+00:00', '--job-id', '54', '--raw', '--subdir', 'DAGS_FOLDER/stock_analysis_dag.py', '--cfg-path', '/tmp/tmpq9f7k5z4']
[2024-01-31T12:27:01.595+0000] {standard_task_runner.py:88} INFO - Job 54: Subtask get_and_store_gpt_advice
[2024-01-31T12:27:01.617+0000] {task_command.py:423} INFO - Running <TaskInstance: stock_analysis_dag.get_and_store_gpt_advice manual__2024-01-31T12:26:47.777766+00:00 [running]> on host de-airflow-vm-instance-1.europe-west10-a.c.dataengineeringfinal-411911.internal
[2024-01-31T12:27:01.656+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='onatpostac@gmail.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='stock_analysis_dag' AIRFLOW_CTX_TASK_ID='get_and_store_gpt_advice' AIRFLOW_CTX_EXECUTION_DATE='2024-01-31T12:26:47.777766+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-01-31T12:26:47.777766+00:00'
[2024-01-31T12:27:01.660+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/deprojectue/miniconda3/envs/airflow_demo/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/deprojectue/miniconda3/envs/airflow_demo/lib/python3.9/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/deprojectue/miniconda3/envs/airflow_demo/lib/python3.9/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/deprojectue/airflow_demo/dags/stock_analysis_dag.py", line 50, in get_and_store_gpt_advice
    test_prompt = generate_gpt_prompt_with_statistics(json.dumps(descriptive_data, indent=2))
  File "/home/deprojectue/airflow_demo/dags/stock_analysis_dag.py", line 31, in generate_gpt_prompt_with_statistics
    for stat_category, stats in descriptive_data.items():
AttributeError: 'str' object has no attribute 'items'
[2024-01-31T12:27:01.663+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=stock_analysis_dag, task_id=get_and_store_gpt_advice, execution_date=20240131T122647, start_date=20240131T122701, end_date=20240131T122701
[2024-01-31T12:27:01.670+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 54 for task get_and_store_gpt_advice ('str' object has no attribute 'items'; 3470)
[2024-01-31T12:27:01.685+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-01-31T12:27:01.693+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
