[2024-01-31T15:10:38.894+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_analysis_to_gcs_dag.process_and_save_data_to_gcs manual__2024-01-31T15:10:30.619153+00:00 [queued]>
[2024-01-31T15:10:38.898+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_analysis_to_gcs_dag.process_and_save_data_to_gcs manual__2024-01-31T15:10:30.619153+00:00 [queued]>
[2024-01-31T15:10:38.898+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 2
[2024-01-31T15:10:38.910+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): process_and_save_data_to_gcs> on 2024-01-31 15:10:30.619153+00:00
[2024-01-31T15:10:38.913+0000] {standard_task_runner.py:60} INFO - Started process 6016 to run task
[2024-01-31T15:10:38.914+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'stock_analysis_to_gcs_dag', 'process_and_save_data_to_gcs', 'manual__2024-01-31T15:10:30.619153+00:00', '--job-id', '77', '--raw', '--subdir', 'DAGS_FOLDER/stock_analysis_to_gcs_dag.py', '--cfg-path', '/tmp/tmpn4k61dgq']
[2024-01-31T15:10:38.916+0000] {standard_task_runner.py:88} INFO - Job 77: Subtask process_and_save_data_to_gcs
[2024-01-31T15:10:38.936+0000] {task_command.py:423} INFO - Running <TaskInstance: stock_analysis_to_gcs_dag.process_and_save_data_to_gcs manual__2024-01-31T15:10:30.619153+00:00 [running]> on host de-airflow-vm-instance-1.europe-west10-a.c.dataengineeringfinal-411911.internal
[2024-01-31T15:10:38.974+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='stock_analysis_to_gcs_dag' AIRFLOW_CTX_TASK_ID='process_and_save_data_to_gcs' AIRFLOW_CTX_EXECUTION_DATE='2024-01-31T15:10:30.619153+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-01-31T15:10:30.619153+00:00'
[2024-01-31T15:10:38.977+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/deprojectue/miniconda3/envs/airflow_demo/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/deprojectue/miniconda3/envs/airflow_demo/lib/python3.9/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/deprojectue/miniconda3/envs/airflow_demo/lib/python3.9/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/deprojectue/airflow_demo/dags/stock_analysis_to_gcs_dag.py", line 16, in process_and_save_to_gcs
    stock_data = json.loads(stock_data_json)
NameError: name 'json' is not defined
[2024-01-31T15:10:38.980+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=stock_analysis_to_gcs_dag, task_id=process_and_save_data_to_gcs, execution_date=20240131T151030, start_date=20240131T151038, end_date=20240131T151038
[2024-01-31T15:10:38.987+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 77 for task process_and_save_data_to_gcs (name 'json' is not defined; 6016)
[2024-01-31T15:10:39.006+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-01-31T15:10:39.013+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
